### PR TITLE
Textafm

### PR DESCRIPTION
**Pull request by turkeytalon**

### CODE REVIEW

**Comment by koheisg** [comment]
@tchikuba 

Thank you for the contribution.
In https://github.com/noracast/podcastfreaks.com/pull/136, textafm has been added so can you skip that commit?

**Comment by naokazuterada** [comment]
@koheisg This PR also included some fixes, so I merged it. (And maybe you mentioned someone else ...)

@turkeytalon Thank you very much !! as always

**Comment by koheisg** [comment]
oops..

**Comment by naokazuterada** [comment]
@koheisg Oh, I misunderstood your comment. sorry. 🤕 

@suginoy [My merge commit override](https://github.com/noracast/podcastfreaks.com/blame/master/data/rss.json#L882-L886) your commit (#136), sorry for that...

**Pull request merged**
